# Generated by Django 4.2.7 on 2023-12-20 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(max_length=5)),
            ],
        ),
        migrations.AlterField(
            model_name='album',
            name='rating_between',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='album.reting'),
        ),
    ]
